### ISSUE TITLE
Automate release cycle

### ISSUE THREAD

**Issue by speqtr** [qwertycoin-org/qwertycoin-zero#11]
TODO:
- configure cmake to create following packages:
  - Linux: `.deb` and `.rpm`;
  - macOS: `.dmg` (with `.app` bundle inside);
  - Windows: NSIS installer;
- integrate Travis CI with GitHub Releases for Linux and macOS packages;
- integrate AppVeyor CI with GitHub Releases for Windows packages.

In ideal case repo admin should be able to push new tag to `master` branch and trigger the following events:
- start CI builds on Travis CI and AppVeyor CI;
- build apps for Linux, macOS and Windows;
- run automated tests for Linux, macOS and Windows;
- if all tests are green then push new release to the GitHub Releases.

**Comment by speqtr** [comment]
@nnian please, add additional thoughts/comments 🙂

**Comment by exploshot** [comment]
It would be great if the macOS Wallet could have qt integrated. The most users have problems to install qt via homebrew and renaming the directory. It's not very simple.

**Comment by speqtr** [comment]
> It would be great if the macOS Wallet could have qt integrated. The most users have problems to install qt via homebrew and renaming the directory. It's not very simple.

It definitely can be simplified. I can adjust build scripts so that all packages on all platforms will be self-contained and won't require any additional actions from end users.

**Comment by exploshot** [comment]
Yes that would be great

**Comment by speqtr** [comment]
OK. I'll implement those changes later this week.

**Comment by nnian** [comment]
The automatic release cycle for our repositories (Qwertycoin, Qwertycoin-gui and Qwertycoin-zero) would be perfect!

But the archives for the gui and zero contains a lot of .dll files as well as various language files for Windows. Can these files also be added to the NSIS?

**Comment by speqtr** [comment]
@nnian yes, sure, all of the files will be bundled inside single installer file, this file will install/unpack all the necessary files into a single directory on users machine during installation process. We can bundle anything we want into this installer.

**Comment by speqtr** [comment]
**UPDATE:** PR for this issue will be available tomorrow. Today I'm handling some final packaging issues for Windows platform.

**Comment by speqtr** [comment]
PR #12 is open. All further updates will be posted there.
