### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by nnian** [qwertycoin-org/qwertycoin-zero#6]
Hi @speqtr since last PR to the @qwertycoin-org Repository we can't build this repo.

`Qt5Network.lib(qdnslookup_win.obj) : error LNK2019: unresolved external symbol DnsFree referenced in function "private: static void __cdecl QDnsLookupRunnable::query(int,class QByteArray const &,class QHostAddress const &,class QDnsLook
upReply *)" (?query@QDnsLookupRunnable@@CAXHAEBVQByteArray@@AEBVQHostAddress@@PEAVQDnsLookupReply@@@Z) [\qwertycoin-zero\build\src\QwertycoinExecutable.vcxproj]
Qt5Network.lib(qdnslookup_win.obj) : error LNK2019: unresolved external symbol DnsQuery_W referenced in function "private: static void __cdecl QDnsLookupRunnable::query(int,class QByteArray const &,class QHostAddress const &,class QDnsL
ookupReply *)" (?query@QDnsLookupRunnable@@CAXHAEBVQByteArray@@AEBVQHostAddress@@PEAVQDnsLookupReply@@@Z) [\qwertycoin-zero\build\src\QwertycoinExecutable.vcxproj]
\qwertycoin-zero\build\src\Release\Qwertycoin.exe : fatal error LNK1120: 2 unresolved externals [\qwertycoin-zero\build\src\QwertycoinExecutable.vcxproj]`

Do you have an idea to solve this?

**Comment by speqtr** [comment]
It looks like a linker issue inside Qt5 framework (Qt5Network lib inparticular). I'll look into it, but I don't think that it is related to latest commit in `qwertycoin-org/qwertycoin`.

**Comment by nnian** [comment]
Fixed here https://github.com/qwertycoin-org/qwertycoin-zero/pull/7

**Comment by nnian** [comment]
@speqtr we can't build this on a fresh Windows Pro 64 Bit. It's still the same issue.

**Comment by speqtr** [comment]
@nnian I'll check this one and post an update later.

**Comment by nnian** [comment]
Thanks! The CI builds are bug free only if we want to create and archive our versions we can not build it on Windows.

Do you have experiences with uploading CI Builds to Gitub Release? https://www.appveyor.com/docs/deployment/github/

**Comment by speqtr** [comment]
> Do you have experiences with uploading CI Builds to Gitub Release?

Yes, I do 🙂

NOTE: Current packaging settings create a simple zip archive when building on Windows. And it's now the best choice to distribute Windows packages, because a lot of things can go wrong and a lot of manual actions are required from the end user in order to unpack and install.

Better choice would be to switch from basic "zip archives" to NSIS installers. NSIS installer will detect and safely remove previously installed version of the app.

**Comment by nnian** [comment]
> Better choice would be to switch from basic "zip archives" to NSIS installers. NSIS installer will detect and safely remove previously installed version of the app.

Yes that's true. But I never used executable installers. Maybe it's the best solution. It would be a dream if every commit (or any increment of the version) would create a new github release with new software versions. So we would be able to automate all this Release Stuff very comfortable. (Windows, macOS, Linux rpm / deb)

**Comment by speqtr** [comment]
@nnian I opened separate issue to discuss those changes. Please, see issue #11.

**Comment by nnian** [comment]
@speqtr any updates to these issues? We still can't compile this Wallet under Windows.
@exploshot can't compile the GUI and this (Zero) Wallet on Windows and macOS

We need new Releases before we switch on height 400,000 to the new Reward Formula.

**Comment by speqtr** [comment]
@nnian I'm working on issue #11 (automated build and deployment scripts for CI). I'm planning to open PR for this changes tomorrow. Once merged, Linux/macOS/Windows binaries will be automatically deployed to GitHub release.

Regarding compile/link issues, most likely something is broken in Hunter's Qt5 formula, so the quick solution is to install pre-compiled Qt5 (5.12.x) from https://qt.io and use it as `cmake -DQt5_DIR=/path to/qt/lib/cmake/Qt5 ...`.

I'm using pre-compiled Qt 5.12.4 and compiling latest versions of qwertycoin gui and zero without any errors on Linux, macOS and Windows.

**Comment by nnian** [comment]
Okay cool =) I've tested it with Qt 5.11 in the past without success. Will try it with Qt 5.12.4. I'm looking forward to your PR.

**Comment by speqtr** [comment]
PR #12 will get all the further updates on deployment scripts.
