### ISSUE TITLE
Hunter download does not work Qt-qtbase

### ISSUE THREAD

**Issue by nnian** [qwertycoin-org/qwertycoin-zero#9]
I can't buld the zero on Windows 32 and 64 Bit. Is hunter using an outdated Qt Path? And how we can fix that?

`cmake -G "Visual Studio 15 2017 Win64" -DBUILD_ALL:BOOL=TRUE ..`

Output:

> Checking Build System
  Creating directories for 'Qt-qtbase'
  Building Custom Rule C:/.hunter/_Base/bc7da32/6d8665b/bd9a8a1/Build/Qt/__qtbase/CMakeLists.txt
  Performing download step (download, verify and extract) for 'Qt-qtbase'
  -- verifying file...
         file='C:/.hunter/_Base/Download/Qt/5.11.3/3f6c0df/qt-everywhere-src-5.11.3.tar.xz'
  -- SHA1 hash of
      C:/.hunter/_Base/Download/Qt/5.11.3/3f6c0df/qt-everywhere-src-5.11.3.tar.xz
    does not match expected value
      expected: '3f6c0df4fa7524ed11557ed55db35ef551cd2782'
        actual: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'
  -- File already exists but hash mismatch. Removing...
  -- Downloading...
     dst='C:/.hunter/_Base/Download/Qt/5.11.3/3f6c0df/qt-everywhere-src-5.11.3.tar.xz'
     timeout='none'
  -- Using src='https://download.qt.io/official_releases/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz'
  -- Retrying...
  -- Using src='https://download.qt.io/official_releases/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz'
  -- Retry after 5 seconds (attempt #2) ...
  -- Using src='https://download.qt.io/official_releases/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz'
  -- Retry after 5 seconds (attempt #3) ...
  -- Using src='https://download.qt.io/official_releases/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz'
  -- Retry after 15 seconds (attempt #4) ...
  -- Using src='https://download.qt.io/official_releases/qt/5.11/5.11.3/single/qt-everywhere-src-5.11.3.tar.xz'
  -- Retry after 60 seconds (attempt #5) ...

**Comment by speqtr** [comment]
It could be just a network lag or something like that.

**Comment by speqtr** [comment]
Hunter uses Qt 5.11.3, it's not the latest version, but at the same time it's not an outdated version (rather "one of the latest").
